
export enum ACTIONS {
    SORT_BY_PRICE,
    SORT_BY_RATING,
    FILTER_PRODUCTS_BY_CATEGORY,
    FILTER_BY_SEARCH,
    CLEAR_FILTERS,
    ADD_TO_CART,
    REMOVE_FROM_CART,
    INCREMENT_QUANTITY,
    DECREMENT_QUANTITY,
    LOAD_PRODUCTS
  }