import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Context from './context/Context'
import './globals.css'
import React from 'react'



export const metadata = {
  title: 'LX Challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Context>
          <Navbar/>
        {children}
        <Footer/>
        </Context>
      </body>
    </html>
  )
}
